<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dianta Laverny Pangaribuan">
<meta name="dcterms.date" content="2024-12-27">

<title>Pengaruh Investasi Penanaman Modal Luar Negeri terhadap PDRB 34 Provinsi di Indonesia Tahun 2023</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="index_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="index_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Investasi Penanaman Modal Luar Negeri terhadap PDRB 34 Provinsi di Indonesia Tahun 2023</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dianta Laverny Pangaribuan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 27, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img"></p>
<figcaption>logo</figcaption>
</figure>
</div>
<style>
p {text-align: justify;}
</style>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Investasi Penanaman Modal Asing (PMA) merupakan salah satu pilar penting dalam pembangunan ekonomi suatu negara, termasuk Indonesia. Dalam era globalisasi saat ini, banyak negara berlomba-lomba untuk menarik investasi asing guna mendorong pertumbuhan ekonomi dan meningkatkan kesejahteraan masyarakat. Indonesia, sebagai negara dengan potensi ekonomi yang besar, telah menjadi salah satu tujuan utama bagi investor asing. PDRB (Produk Domestik Regional Bruto) sebagai indikator utama pertumbuhan ekonomi suatu daerah menjadi sangat relevan untuk dianalisis dalam konteks ini.</p>
<p>Pentingnya PMA tidak hanya terletak pada besarnya aliran dana yang masuk ke dalam negeri, tetapi juga pada dampaknya terhadap struktur ekonomi dan lapangan kerja di berbagai provinsi. Dengan adanya investasi asing, diharapkan terjadi transfer teknologi, peningkatan keterampilan sumber daya manusia, dan pengembangan infrastruktur yang pada akhirnya akan berkontribusi pada peningkatan PDRB.</p>
<p>Namun, meskipun potensi keuntungan dari investasi asing sangat besar, terdapat tantangan yang harus dihadapi. Berbagai faktor, seperti stabilitas politik, kebijakan pemerintah, dan kondisi ekonomi global, dapat mempengaruhi keputusan investasi dan dampaknya terhadap PDRB. Oleh karena itu, penelitian ini bertujuan untuk menganalisis pengaruh investasi penanaman modal luar negeri terhadap PDRB provinsi di Indonesia tahun 2023.</p>
<p>Melalui penelitian ini, diharapkan dapat memberikan pemahaman yang lebih mendalam mengenai hubungan antara PMA dan pertumbuhan ekonomi regional di Indonesia. Hasil penelitian ini juga diharapkan dapat menjadi acuan bagi pemb policymakers dalam merumuskan kebijakan yang lebih efektif untuk menarik investasi asing serta memaksimalkan dampak positifnya terhadap PDRB.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penelitian ini menggunakan data yang dikumpulkan melalui laporan tahunan Badan Pusat Statistik (BPS). Penelitian ini melibatkan dua variabel utama, yaitu variabel independen (X) berupa investasi penanaman modal asing (PMA) dan variabel dependen (Y) berupa Produk Domestik Regional Bruto (PDRB) di 34 provinsi di Indonesia pada tahun 2023. Analisis dilakukan untuk mengevaluasi hubungan antara kedua variabel tersebut dalam konteks pertumbuhan ekonomi regional.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="1">
<li>Seberapa besar kontribusi investasi penanaman modal luar negeri terhadap PDRB provinsi?</li>
<li>Apa saja faktor yang mempengaruhi PDRB provinsi ?</li>
<li>Apa tantangan yang dihadapi Indonesia dari investasi asing?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan penelitian ini dirumuskan untuk memberikan manfaat bagi pemerintah dan masyarakat, dengan fokus pada pengaruh investasi penanaman modal luar negeri terhadap PDRB provinsi :</p>
<p><em>1. Bagi Pemerintah</em></p>
<p>Memberikan rekomendasi kebijakan yang berbasis data untuk meningkatkanivestasi asing yang masuk ke indonesia terhadap PDRB indonesia. Mengidentifikasi strategi yang dapat digunakan pemerintah untuk mengoptimalkan pemanfaatan investasi asing, sehingga dapat mendukung pertumbuhan ekonomi yang berkelanjutan.</p>
<p><em>2. Bagi Masyarakat</em></p>
<p>Meningkatkan kesadaran publik mengenai peran investasi asing terhadap PDRB indonesia dan dampaknya terhadap kesejahteraan masyarakat. Mendorong partisipasi masyarakat dalam proses pengambilan keputusan terkait kebijakan investasi asing, dengan memahami implikasi dari kebijakan tersebut terhadap kehidupan sehari-hari mereka.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Ini tidak wajib ada di packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p><em>1. Konsep Penanaman Modal Asing (PMA)</em></p>
<p>Penanaman Modal Asing (PMA) merupakan investasi yang dilakukan oleh investor asing di suatu negara dengan tujuan untuk mendapatkan keuntungan. Menurut UNCTAD (2021), PMA dapat berkontribusi pada pengembangan ekonomi melalui penciptaan lapangan kerja, transfer teknologi, dan peningkatan daya saing industri lokal.</p>
<p><em>2. Hubungan PMA dan Pertumbuhan Ekonomi</em></p>
<p>Banyak penelitian menunjukkan bahwa ada hubungan positif antara PMA dan pertumbuhan ekonomi. Misalnya, penelitian oleh Alfaro et al.&nbsp;(2004) menunjukkan bahwa PMA dapat meningkatkan PDRB melalui peningkatan produktivitas dan inovasi. Penelitian ini juga menekankan pentingnya konteks lokal, seperti kualitas institusi dan infrastruktur, dalam memfasilitasi dampak positif PMA.</p>
<p><em>3. PDRB sebagai Indikator Pertumbuhan Ekonomi</em></p>
<p>PDRB adalah ukuran nilai total barang dan jasa yang dihasilkan dalam suatu wilayah selama periode tertentu. Menurut Badan Pusat Statistik (2022), PDRB mencerminkan kinerja ekonomi suatu daerah dan dapat dipengaruhi oleh berbagai faktor, termasuk investasi, konsumsi, dan ekspor.</p>
<p><em>4. Penelitian Terkait di Indonesia</em></p>
<p>Di Indonesia, beberapa studi telah dilakukan untuk mengeksplorasi hubungan antara PMA dan PDRB. Penelitian oleh Sari dan Susanti (2020) menemukan bahwa PMA memiliki dampak signifikan terhadap PDRB provinsi, terutama di sektor industri dan jasa. Selain itu, penelitian oleh Prasetyo (2021) menunjukkan bahwa kebijakan pemerintah dalam menarik investasi asing sangat berpengaruh terhadap peningkatan PDRB di daerah-daerah tertentu.</p>
<p><em>5. Faktor-faktor yang Mempengaruhi PMA dan PDRB</em></p>
<p>Faktor-faktor seperti stabilitas politik, kebijakan perpajakan, dan infrastruktur juga memainkan peran penting dalam menarik PMA. Penelitian oleh Nugroho dan Yulianto (2019) menyatakan bahwa daerah dengan infrastruktur yang baik dan kebijakan yang mendukung lebih mampu menarik investasi asing, yang akan berkontribusi pada peningkatan PDRB.</p>
<p>Studi pustaka ini menunjukkan bahwa PMA memiliki potensi untuk meningkatkan PDRB di Indonesia, namun dampaknya dapat bervariasi tergantung pada konteks dan faktor lokal. Penelitian lebih lanjut diperlukan untuk menganalisis lebih dalam hubungan ini, terutama pada tahun 2023, di mana kondisi ekonomi global dan domestik mengalami perubahan yang signifikan.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Penelitian ini menggunakan data yang diambil dari Badan Pusat Statistik (BPS), dengan variabel X merupakan investasi penanaman modal asing, dan variabel Y merupakan PDRB provinsi di Indonesia tahun 2023. Kemudian data diolah agar linier sehingga menghasilkan data sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/invest/data.xlsx"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(data, <span class="at">format =</span> <span class="st">"html"</span>, <span class="at">caption =</span> <span class="st">"Tabel 1: Data linier"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>, <span class="at">position =</span> <span class="st">"center"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>, <span class="at">background =</span> <span class="st">"#D3D3D3"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_header_above</span>(<span class="fu">c</span>(<span class="st">" "</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">"Data PMA dan PDRB"</span> <span class="ot">=</span> <span class="fu">ncol</span>(data) <span class="sc">-</span> <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">1</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>, <span class="at">border_right =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Tabel 1: Data linier</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Data PMA dan PDRB
</div></th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; background-color: rgba(211, 211, 211, 255) !important;">Provinsi</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; background-color: rgba(211, 211, 211, 255) !important;">X</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; background-color: rgba(211, 211, 211, 255) !important;">Y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Aceh</td>
<td style="text-align: right;">12.423600</td>
<td style="text-align: right;">23.84612</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Sumatera Utara</td>
<td style="text-align: right;">13.982126</td>
<td style="text-align: right;">25.37817</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Sumatera Barat</td>
<td style="text-align: right;">11.701063</td>
<td style="text-align: right;">24.16615</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Riau</td>
<td style="text-align: right;">14.529587</td>
<td style="text-align: right;">25.35456</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Jambi</td>
<td style="text-align: right;">10.716637</td>
<td style="text-align: right;">24.10334</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Sumatera Selatan</td>
<td style="text-align: right;">14.206606</td>
<td style="text-align: right;">24.86497</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Bengkulu</td>
<td style="text-align: right;">11.239804</td>
<td style="text-align: right;">22.99076</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Lampung</td>
<td style="text-align: right;">12.304106</td>
<td style="text-align: right;">24.52744</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Kepulauan Bangka Belitung</td>
<td style="text-align: right;">11.191342</td>
<td style="text-align: right;">23.05187</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Kepulauan Riau</td>
<td style="text-align: right;">13.546454</td>
<td style="text-align: right;">24.22548</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">DKI Jakarta</td>
<td style="text-align: right;">15.390357</td>
<td style="text-align: right;">26.56477</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Jawa Barat</td>
<td style="text-align: right;">15.929800</td>
<td style="text-align: right;">26.29360</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Jawa Tengah</td>
<td style="text-align: right;">14.262565</td>
<td style="text-align: right;">25.85718</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">DI Yogyakarta</td>
<td style="text-align: right;">10.736397</td>
<td style="text-align: right;">23.61746</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Jawa Timur</td>
<td style="text-align: right;">15.371759</td>
<td style="text-align: right;">26.41144</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Banten</td>
<td style="text-align: right;">15.308774</td>
<td style="text-align: right;">25.12279</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Bali</td>
<td style="text-align: right;">13.602936</td>
<td style="text-align: right;">24.03511</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Nusa Tenggara Barat</td>
<td style="text-align: right;">13.057078</td>
<td style="text-align: right;">23.53504</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Nusa Tenggara Timur</td>
<td style="text-align: right;">11.730453</td>
<td style="text-align: right;">23.27679</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Kalimantan Barat</td>
<td style="text-align: right;">13.103181</td>
<td style="text-align: right;">24.03552</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Kalimantan Tengah</td>
<td style="text-align: right;">13.455401</td>
<td style="text-align: right;">23.76228</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Kalimantan Selatan</td>
<td style="text-align: right;">12.700464</td>
<td style="text-align: right;">24.01649</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Kalimantan Timur</td>
<td style="text-align: right;">14.102718</td>
<td style="text-align: right;">25.15833</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Kalimantan Utara</td>
<td style="text-align: right;">14.056180</td>
<td style="text-align: right;">23.41301</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Sulawesi Utara</td>
<td style="text-align: right;">12.224404</td>
<td style="text-align: right;">23.56800</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Sulawesi Tengah</td>
<td style="text-align: right;">15.795698</td>
<td style="text-align: right;">24.27041</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Sulawesi Selatan</td>
<td style="text-align: right;">12.726948</td>
<td style="text-align: right;">24.90161</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Sulawesi Tenggara</td>
<td style="text-align: right;">13.013218</td>
<td style="text-align: right;">23.59219</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Gorontalo</td>
<td style="text-align: right;">10.428216</td>
<td style="text-align: right;">22.35982</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Sulawesi Barat</td>
<td style="text-align: right;">10.098232</td>
<td style="text-align: right;">22.49059</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Maluku</td>
<td style="text-align: right;">11.574021</td>
<td style="text-align: right;">22.48953</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Maluku Utara</td>
<td style="text-align: right;">15.424588</td>
<td style="text-align: right;">22.86504</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Papua Barat</td>
<td style="text-align: right;">10.268131</td>
<td style="text-align: right;">22.54088</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Papua Barat Daya</td>
<td style="text-align: right;">11.440355</td>
<td style="text-align: right;">22.00710</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Papua</td>
<td style="text-align: right;">9.024011</td>
<td style="text-align: right;">22.82420</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Papua Selatan</td>
<td style="text-align: right;">11.365585</td>
<td style="text-align: right;">21.86620</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Papua Tengah</td>
<td style="text-align: right;">13.782987</td>
<td style="text-align: right;">23.43379</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Papua Pegunungan</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">21.61666</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/invest/data.xlsx"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Provinsi             X     Y
  &lt;chr&gt;            &lt;dbl&gt; &lt;dbl&gt;
1 Aceh              12.4  23.8
2 Sumatera Utara    14.0  25.4
3 Sumatera Barat    11.7  24.2
4 Riau              14.5  25.4
5 Jambi             10.7  24.1
6 Sumatera Selatan  14.2  24.9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>data,<span class="fu">aes</span>(<span class="at">x=</span>X,<span class="at">y=</span>Y))<span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"orange"</span>,<span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"hubungan PMA dan PDRB provinsi di Indonesia"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"Investasi Penanaman Modal Luar Negeri"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"PDRB"</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"sumber: Badan Pusat Statistik (BPS)"</span>)<span class="sc">+</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode yang dipilih adalah regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen. Penelitian ini bermaksud mencari hubungan antara PMA dan PDRB. Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah PDRB dan <span class="math inline">\(x_t\)</span> adalah PMA.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Dari regresi yang telah dilakukan menghasilkan data sebagai berikut:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>variable</th>
<th>Coefficients</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>20.00573</td>
</tr>
<tr class="even">
<td>X</td>
<td>0.31150</td>
</tr>
<tr class="odd">
<td>p-value</td>
<td>3.706e-06</td>
</tr>
<tr class="even">
<td>Multiple R-squared</td>
<td>0.4526</td>
</tr>
<tr class="odd">
<td>Adjusted R-squared</td>
<td>0.4374</td>
</tr>
</tbody>
</table>
<p>Maka didapatkan : <span class="math display">\[
y_{t}=\ 20.00573 + \ 0.31150 x_t+\mu_t
\]</span> Intercept yang signifikan menunjukkan bahwa jika nilai investasi PMLN (X) sama dengan nol, nilai PDRB (Y) di provinsi Indonesia akan berada pada angka sekitar 20.00573. Hal ini memberi gambaran bahwa faktor lain (selain PMLN) turut berperan dalam menjelaskan PDRB, dan intercept ini mencerminkan pengaruh variabel lain tersebut, meskipun p-value yang sangat kecil menunjukkan bahwa nilai intercept ini signifikan secara statistik.</p>
<p>Koefisien untuk PMLN (X) sebesar 0.31150 menunjukkan bahwa setiap peningkatan satu unit dalam investasi penanaman modal luar negeri diharapkan dapat meningkatkan PDRB sebesar 0.31150 unit, dengan asumsi faktor lain tetap konstan. PMLN memiliki hubungan positif yang signifikan dengan PDRB. P-value yang sangat kecil (3.71e-06) menunjukkan bahwa hubungan ini sangat signifikan secara statistik, yang berarti bahwa investasi PMLN berpengaruh signifikan terhadap PDRB di provinsi Indonesia pada tahun 2023.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/invest"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data.xlsx"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>reg2<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>data,Y<span class="sc">~</span>X)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.94546 -0.62626 -0.04072  0.74177  1.76494 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 20.00573    0.73127  27.358  &lt; 2e-16 ***
X            0.31150    0.05709   5.456 3.71e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9493 on 36 degrees of freedom
Multiple R-squared:  0.4526,    Adjusted R-squared:  0.4374 
F-statistic: 29.77 on 1 and 36 DF,  p-value: 3.706e-06</code></pre>
</div>
</div>
<p>R-squared sebesar 0.4526 menunjukkan bahwa model regresi ini dapat menjelaskan sekitar 45.26% variasi dalam PDRB yang dipengaruhi oleh investasi penanaman modal luar negeri (PMLN). Meskipun hubungan antara PMLN dan PDRB signifikan, model ini belum dapat menjelaskan seluruh variasi dalam PDRB, yang mengindikasikan kemungkinan adanya faktor lain selain PMLN yang turut berperan dalam variasi tersebut. Sementara itu, Adjusted R-squared yang sedikit lebih rendah, yaitu 0.4374, menunjukkan bahwa setelah memperhitungkan jumlah prediktor dalam model (dalam hal ini hanya satu variabel independen), sekitar 43.74% variasi dalam PDRB masih dapat dijelaskan oleh model. Selain itu, nilai F-statistic sebesar 29.77 dengan p-value 3.706e-06 mengindikasikan bahwa model regresi ini secara keseluruhan sangat signifikan dalam menjelaskan variasi PDRB. P-value yang sangat kecil ini menegaskan bahwa model ini dapat digunakan dengan tingkat keyakinan yang tinggi untuk memprediksi PDRB, menunjukkan bahwa PMLN memiliki peran yang signifikan dalam mempengaruhi pertumbuhan ekonomi daerah di Indonesia.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Penanaman Modal Asing (PMA) dapat berpengaruh signifikan terhadap Produk Domestik Regional Bruto (PDRB) di suatu daerah. Investasi asing sering kali membawa aliran modal yang besar, yang digunakan untuk membangun infrastruktur, meningkatkan kapasitas produksi, dan menciptakan lapangan kerja baru, yang semuanya dapat mendorong pertumbuhan ekonomi dan meningkatkan PDRB. Selain itu, PMA juga memungkinkan transfer teknologi dan keterampilan yang dapat meningkatkan produktivitas serta efisiensi di sektor-sektor terkait. Investasi asing sering berfokus pada sektor-sektor ekspor, yang dapat meningkatkan pendapatan dari perdagangan internasional dan memberi kontribusi langsung pada PDRB. Meskipun demikian, dampak PMA terhadap PDRB tidak selalu merata dan bergantung pada kualitas investasi, kebijakan pemerintah, serta kondisi ekonomi dan sosial setempat. Oleh karena itu, meskipun PMA memiliki potensi besar untuk mendorong pertumbuhan ekonomi, keberhasilannya sangat dipengaruhi oleh berbagai faktor yang mendukung atau menghambatnya.</p>
<p>Berdasarkan hasil analisis regresi linier sederhana yang dilakukan untuk menguji pengaruh investasi penanaman modal luar negeri terhadap PDRB 34 provinsi Indonesia pada tahun 2023, dapat disimpulkan bahwa terdapat hubungan yang signifikan antara kedua variabel tersebut. Koefisien regresi untuk PMA sebesar 0.31150 menunjukkan bahwa setiap peningkatan satu unit pada PMA dapat meningkatkan PDRB sebesar 0.31150 unit, dengan tingkat signifikansi yang sangat tinggi (p-value &lt; 0.01).</p>
<p>Model regresi ini menunjukkan bahwa PMA memiliki pengaruh yang signifikan terhadap pertumbuhan ekonomi di tingkat provinsi. Hal ini tercermin dari nilai F-statistik yang sangat signifikan (p-value = 3.706e-06) dan R-squared sebesar 0.4526, yang berarti sekitar 45.26% variasi dalam PDRB dapat dijelaskan oleh variabel PMA.</p>
<p>Namun, meskipun hasil ini menunjukkan adanya pengaruh yang kuat, nilai R-squared yang moderat juga mengindikasikan bahwa faktor-faktor lain yang tidak dimasukkan dalam model ini mungkin turut memengaruhi PDRB. Oleh karena itu, perlu dilakukan penelitian lebih lanjut dengan mempertimbangkan variabel lain yang mungkin berperan dalam dinamika perekonomian.</p>
<p>Secara keseluruhan, penelitian ini memberikan bukti empiris bahwa investasi penanaman modal luar negeri memiliki dampak positif yang signifikan terhadap pertumbuhan ekonomi di Indonesia. Kebijakan yang mendukung peningkatan investasi asing diharapkan dapat berkontribusi pada pengembangan ekonomi yang lebih merata di seluruh provinsi di Indonesia.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>UNCTAD. (2021). World Investment Report 2021. United Nations Conference on Trade and Development.</p>
<p>Alfaro, L., Chanda, A., Kalemli-Ozcan, S., &amp; Sayek, S. (2004). “FDI and Economic Growth: The Role of Local Financial Markets.” Journal of International Economics, 64(1), 89-112.</p>
<p>Badan Pusat Statistik. (2022). Statistik Ekonomi Provinsi. Jakarta: BPS.</p>
<p>Sari, D. P., &amp; Susanti, R. (2020). “Pengaruh Penanaman Modal Asing Terhadap PDRB di Provinsi Jawa Barat.” Jurnal Ekonomi dan Pembangunan, 18(2), 123-135.</p>
<p>Prasetyo, R. (2021). “Dampak Kebijakan Investasi Terhadap PDRB di Indonesia.” Jurnal Ekonomi dan Kebijakan Publik, 10(1), 45-60.</p>
<p>Nugroho, A., &amp; Yulianto, E. (2019). “Faktor-Faktor yang Mempengaruhi Investasi Penanaman Modal Asing di Indonesia.” Jurnal Bisnis dan Manajemen, 8(3), 210-225.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>
